# If you wish to use FLAT (SQLite) just set MySQL to False.
Database:
  MySQL: False
  host: localhost
  database: minecraft
  username: minecraft
  password: minecraft
  port: 3306
# WhiteListed Worlds
Worlds:
  - world
Permissions:
  AdminCommand: "cp.admin"